// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio.API.DataAccess;

#nullable disable

namespace Portfolio.API.DataAccess.SQLite.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    partial class PortfolioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("Portfolio.API.DataAccess.Entities.ApiTracker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<string>("City")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("InternetProvider")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpLocationError")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsMobile")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsProxy")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("RoutePath")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tracking");
                });

            modelBuilder.Entity("Portfolio.API.DataAccess.Entities.Password", b =>
                {
                    b.Property<string>("HashValue")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("HashValue");

                    b.ToTable("Passwords");
                });
#pragma warning restore 612, 618
        }
    }
}
